### ISSUE TITLE
Make dynamic imports work

### ISSUE THREAD

**Issue by lgraziani2712** [AsaAyers/js-hyperclick-core#1]
### Proposal

It would be good if we could have the dynamic import working with js-hyperclick.

### Links and documentation

- https://github.com/tc39/proposal-dynamic-import
- https://github.com/airbnb/babel-plugin-dynamic-import-node

**Comment by AsaAyers** [comment]
I don't see how that could work. If the import is dynamic, how can I know which file to navigate to?

Sorry for the long response time. Somehow I wasn't watching this repo and didn't get a notification.

**Comment by lgraziani2712** [comment]
> how can I know which file to navigate to?

Good question is good hah. I forget about that little detail.

I'll close the issue.
